### ISSUE TITLE
[Bug] Cant install plugin - Invalid URI

### ISSUE THREAD

**Issue by GameveD** [lokinmodar/Echoglossian#10]
Dalamud testing is enabled.
Game restarted after enabling testing.
Other plugins, like FPS Plugin, working fine.

I will note, that game running on linux using Lutris, but i think it's not important.

Log:
```
--------------------------------
17:36:31.919 | DBG [PLUGINM] Installing plugin Echoglossian (testing=True)
--------------------------------
17:36:32.773 | DBG [PLUGINM] Extracting to C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305
--------------------------------
17:36:32.790 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\es
--------------------------------
17:36:32.799 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\Font
--------------------------------
17:36:32.847 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\pt-BR
--------------------------------
17:36:32.850 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\TempPE
--------------------------------
17:36:32.878 | INF [PLUGINM] Installed plugin Echoglossian (testing=True)
--------------------------------
17:36:32.879 | INF [PLUGINM] Loading plugin Echoglossian
--------------------------------
17:36:32.889 | INF [LOCALPLUGIN] Loading Echoglossian.dll
--------------------------------
17:36:32.967 | VRB [HM] Detected hook trampoline at 1405CE540, stopping jump resolution.
--------------------------------
17:36:32.981 | VRB [HM] Detected hook trampoline at 140E95490, stopping jump resolution.
--------------------------------
17:36:33.109 | ERR [LOCALPLUGIN] Error while loading Echoglossian
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Echoglossian.Echoglossian' threw an exception.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder..ctor(String uri)
   at Echoglossian.Echoglossian.get_AssemblyDirectory() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 37
   at Echoglossian.Echoglossian..cctor() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 30
   --- End of inner exception stack trace ---
   at Echoglossian.Echoglossian.set_Common(XivCommonBase value) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 135
   at Echoglossian.Echoglossian..ctor(DalamudPluginInterface dalamudPluginInterface, Framework pframework, CommandManager pCommandManager, GameGui pGameGui, ToastGui pToastGui) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 95
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 315
--------------------------------
17:36:33.111 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Echoglossian.Echoglossian' threw an exception.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder..ctor(String uri)
   at Echoglossian.Echoglossian.get_AssemblyDirectory() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 37
   at Echoglossian.Echoglossian..cctor() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 30
   --- End of inner exception stack trace ---
   at Echoglossian.Echoglossian.set_Common(XivCommonBase value) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 135
   at Echoglossian.Echoglossian..ctor(DalamudPluginInterface dalamudPluginInterface, Framework pframework, CommandManager pCommandManager, GameGui pGameGui, ToastGui pToastGui) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 95
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 315
   at Dalamud.Plugin.Internal.PluginManager.LoadPlugin(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 547
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 499

```

**Comment by lokinmodar** [comment]
It does make all sense the Lutris + Linux info. I'm gonna have to ask for help to treat this as I don't run the game on Linux. Can you provide more info regarding your gaming setup and configs?

**Comment by lokinmodar** [comment]
Can you try this: 
![image](https://user-images.githubusercontent.com/15621921/135762276-475a32c3-7f3d-41e1-a69e-3e706e1ec2c0.png)

**Comment by GameveD** [comment]
Will try right now.

**Comment by GameveD** [comment]
So, looks like i got same error.


As i launched game i get pop up telling me install chromium dependency.
As i install that from main menu, it crash game on 100% bar.
When i installed after loging in game world, it just installed (i was need to install this because it was blocking focus from other Dalamun windows, i was cannot press any button)

![Снимок экрана от 2021-10-03 19-17-36](https://user-images.githubusercontent.com/4355532/135762831-7476705b-31b7-49b1-9a02-5403fcc0ef40.png)

```
--------------------------------
19:19:35.943 | VRB WindowSystem "DalamudCore" Window "Установщик плагинов (TESTING)###XlPluginInstaller" has focus now
--------------------------------
19:19:36.892 | DBG [PLUGINM] Installing plugin Echoglossian (testing=True)
--------------------------------
19:19:37.612 | DBG [PLUGINM] Extracting to C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305
--------------------------------
19:19:37.627 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\es
--------------------------------
19:19:37.636 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\Font
--------------------------------
19:19:37.683 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\pt-BR
--------------------------------
19:19:37.685 | VRB [PLUGINM] ZipFile name is null or empty, treating as a directory: C:\users\user\AppData\Roaming\XIVLauncher\installedPlugins\Echoglossian\2.0.2109.1305\TempPE
--------------------------------
19:19:37.712 | INF [PLUGINM] Installed plugin Echoglossian (testing=True)
--------------------------------
19:19:37.712 | INF [PLUGINM] Loading plugin Echoglossian
--------------------------------
19:19:37.724 | INF [LOCALPLUGIN] Loading Echoglossian.dll
--------------------------------
19:19:37.799 | VRB [HM] Detected hook trampoline at 1405CE540, stopping jump resolution.
--------------------------------
19:19:37.813 | VRB [HM] Detected hook trampoline at 140E95490, stopping jump resolution.
--------------------------------
19:19:37.954 | ERR [LOCALPLUGIN] Error while loading Echoglossian
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Echoglossian.Echoglossian' threw an exception.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder..ctor(String uri)
   at Echoglossian.Echoglossian.get_AssemblyDirectory() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 37
   at Echoglossian.Echoglossian..cctor() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 30
   --- End of inner exception stack trace ---
   at Echoglossian.Echoglossian.set_Common(XivCommonBase value) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 135
   at Echoglossian.Echoglossian..ctor(DalamudPluginInterface dalamudPluginInterface, Framework pframework, CommandManager pCommandManager, GameGui pGameGui, ToastGui pToastGui) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 95
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 315
--------------------------------
19:19:37.956 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Echoglossian.Echoglossian' threw an exception.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder..ctor(String uri)
   at Echoglossian.Echoglossian.get_AssemblyDirectory() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 37
   at Echoglossian.Echoglossian..cctor() in I:\Dante\tataru-to-dalamud\Echoglossian\Glossian.cs:line 30
   --- End of inner exception stack trace ---
   at Echoglossian.Echoglossian.set_Common(XivCommonBase value) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 135
   at Echoglossian.Echoglossian..ctor(DalamudPluginInterface dalamudPluginInterface, Framework pframework, CommandManager pCommandManager, GameGui pGameGui, ToastGui pToastGui) in I:\Dante\tataru-to-dalamud\Echoglossian\Echoglossian.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 95
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 315
   at Dalamud.Plugin.Internal.PluginManager.LoadPlugin(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 547
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 499
--------------------------------
19:19:37.971 | VRB WindowSystem "DalamudCore" Window "Установщик плагинов (TESTING)###XlPluginInstaller" lost focus
--------------------------------
19:19:39.108 | VRB WindowSystem "DalamudCore" Window "Установщик плагинов (TESTING)###XlPluginInstaller" has focus now
--------------------------------
19:19:39.800 | VRB WindowSystem "DalamudCore" Window "Установщик плагинов (TESTING)###XlPluginInstaller" lost focus
{ } [ Send ]
```

**Comment by GameveD** [comment]
About setup.

Lutris and XIVLauncher:
It's installed using install script "XIVLauncher-Wine6 version" from https://lutris.net/games/final-fantasy-xiv-online/
Direct link https://lutris.net/games/install/29349/view
It's create new wine prefix, installs dotnet48 and vcrun2019, silently installs XIVLauncher and set some other settings.
I edited this one by replacing wine (known as runner) from "lutris-6.10-7-x86_64" to "lutris-ge-lol-6.16-2-x86_64".

FFXIV location is in other place.
Originaly FFXIV was downloaded and installed from original launcher from steam.
And steam was installed as Flatpack.
So it's long path to game folder that i cut by creating link (ln -s) to that folder from ~/Games/
And that all. 

Current env settings in Lutris^
![изображение](https://user-images.githubusercontent.com/4355532/135763103-94d44a54-c2e3-43e9-ab0d-d8bd502436b2.png)

**Comment by GameveD** [comment]
Switched to "lutris-6.10-7-x86_64"
Still same error.
Also Dalamud asking install that dependency every time i entering the game.

**Comment by lokinmodar** [comment]
This is odd. the Harmony env variable should fix any error regarding installs. Does this happen only with this plugin? Do you have any firewall rule preventing connections?

**Comment by lokinmodar** [comment]
Can you check if the file ``Wiki82.profile.xml`` is present in the folder XIVLauncher\installedPlugins\Echoglossian directory?

**Comment by lokinmodar** [comment]
Can you check this: https://discord.com/channels/581875019861328007/850387047927250944/894273896495321108

**Comment by GameveD** [comment]
>Does this happen only with this plugin?

No, but stuff is wierd.
That Dependency installing Browser host plugin.
But if i uninstall it it cannot be instaled again. (other error)

I try install DelvUI
It fails with another one error.
But
It's mark as installed and even open setting.

>Do you have any firewall rule preventing connections?

Well yes, but actually no.
I monitoring connections and right now it's allow to go. Here no problems with that,

>Can you check if the file Wiki82.profile.xml is present in the folder XIVLauncher\installedPlugins\Echoglossian directory?
It's exist and full of data. 

I will try move symlink of game dir to wine prefix and see if it change anything.

**Comment by GameveD** [comment]
Well, it's re-downloading game. 
It's take some time (~30 min)

**Comment by lokinmodar** [comment]
Let me know if these adjustments you are making solve the issue

**Comment by GameveD** [comment]
As for now re-instalation in drive_c in user dir didn't help.

**Comment by lokinmodar** [comment]
Fixed in the current release. Closing the issue. Please install the new version from FFXIVQuickLaucher
