### ISSUE TITLE
[Bug] Cant install on Dalamud 

### ISSUE THREAD

**Issue by CarloGabriel** [lokinmodar/Echoglossian#20]
can't install, i click to install, time goes by and nothing happens

--------------------------------
14:35:46.709 | INF [LOCALPLUGIN] Loading FPSPlugin.dll
--------------------------------
14:35:46.711 | INF [T3] DUI OK!
--------------------------------
14:35:46.718 | INF Dalamud is ready.
--------------------------------
14:35:46.738 | INF [LOCALPLUGIN] Finished loading FPSPlugin.dll
--------------------------------
14:35:46.738 | INF [PLUGINM] Loading plugin PingPlugin
--------------------------------
14:35:46.797 | INF [LOCALPLUGIN] Loading PingPlugin.dll
--------------------------------
14:35:46.812 | INF [PingPlugin] Loading lang data from PingPlugin.Lang.lang_en.json
--------------------------------
14:35:46.885 | INF [LOCALPLUGIN] Finished loading PingPlugin.dll
--------------------------------
14:35:46.885 | INF [PLUGINM] Loading plugin Pixel Perfect
--------------------------------
14:35:46.912 | INF [LOCALPLUGIN] Loading PixelPerfect.dll
--------------------------------
14:35:46.923 | INF [LOCALPLUGIN] Finished loading PixelPerfect.dll
--------------------------------
14:36:40.991 | INF [PLUGINM] Starting plugin update
--------------------------------
14:36:40.993 | INF [PLUGINM] Plugin update OK.
--------------------------------
14:37:17.200 | INF [PLUGINR] Fetching repo: https://raw.githubusercontent.com/goatcorp/DalamudPlugins/api4/pluginmaster.json
--------------------------------
14:39:28.483 | ERR Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (One or more errors occurred. (A task was canceled.))
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Dalamud.Interface.Internal.Windows.PluginInstallerWindow.<>c__DisplayClass54_0.<DrawAvailablePlugin>b__2(Task`1 task) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstallerWindow.cs:line 1213
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
--- End of stack trace from previous location ---
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Dalamud.Interface.Internal.Windows.PluginInstallerWindow.<>c__DisplayClass54_0.<DrawAvailablePlugin>b__2(Task`1 task) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginInstallerWindow.cs:line 1213
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
{ } [ Send ]

**Comment by lokinmodar** [comment]
This issue looks to be related to internet connection timeout while downloading the plugin files... I suggest you check your connection and retry. If it does not install, ping me.

**Comment by CarloGabriel** [comment]
tem outro diretório ou link pra eu baixar por fora e instalar?

**Comment by wertir2093** [comment]
Same problem, same error. Tryed differents system and connection... cant install.

**Comment by lokinmodar** [comment]
Hello. Contact me in discord DanteSS#2200, please

Em sáb, 13 de nov de 2021 05:34, wertir2093 ***@***.***>
escreveu:

**Comment by Loseriana** [comment]
Any news in how to fix this issue ?

**Comment by lokinmodar** [comment]
This  is related to github being an ass when the launcher tries to download the plugin files. For now the solution is to check your connection and retry installing later. Or contact me through discord

> Hello. Contact me in discord DanteSS#2200, >.
