### ISSUE TITLE
[Bug] Cant install on API4

### ISSUE THREAD

**Issue by Lanselotto** [lokinmodar/Echoglossian#8]
When i try to install EchoGlossian on API4 this appens
![image](https://user-images.githubusercontent.com/39704475/134916715-05ffc1a2-cf6a-4139-8ce1-adab184c4578.png)

**Comment by lokinmodar** [comment]
can you open the /xldev Dalamud Log window and paste the error? i think it
may be some missing dll in the plugin folder...

Em seg., 27 de set. de 2021 às 10:22, Lanselotto ***@***.***>
escreveu:

**Comment by lokinmodar** [comment]
```
10:33:40.908 | VRB WindowSystem "DalamudCore" Window "Plugin Installer (TESTING)###XlPluginInstaller" has focus now
--------------------------------
10:33:47.664 | DBG [PLUGINM] Installing plugin Echoglossian (testing=False)
--------------------------------
10:33:47.670 | INF LASTEXCEPTION:eyJXaGVuIjoiMjAyMS0wOS0yN1QxMDozMzo0Ny42NzAxMDUzLTAzOjAwIiwiSW5mbyI6IlN5c3RlbS5JbnZhbGlkT3BlcmF0aW9uRXhjZXB0aW9uOiBBbiBpbnZhbGlkIHJlcXVlc3QgVVJJIHdhcyBwcm92aWRlZC4gVGhlIHJlcXVlc3QgVVJJIG11c3QgZWl0aGVyIGJlIGFuIGFic29sdXRlIFVSSSBvciBCYXNlQWRkcmVzcyBtdXN0IGJlIHNldC5cclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwLkh0dHBDbGllbnQuUHJlcGFyZVJlcXVlc3RNZXNzYWdlKEh0dHBSZXF1ZXN0TWVzc2FnZSByZXF1ZXN0KVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENsaWVudC5TZW5kQXN5bmMoSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3QsIEh0dHBDb21wbGV0aW9uT3B0aW9uIGNvbXBsZXRpb25PcHRpb24sIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5QbHVnaW5NYW5hZ2VyLkluc3RhbGxQbHVnaW5Bc3luYyhSZW1vdGVQbHVnaW5NYW5pZmVzdCByZXBvTWFuaWZlc3QsIEJvb2xlYW4gdXNlVGVzdGluZywgUGx1Z2luTG9hZFJlYXNvbiByZWFzb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFBsdWdpbk1hbmFnZXIuY3M6bGluZSA0MTIiLCJDb250ZXh0IjoiW1BMVUdJTlddIFBsdWdpbiBpbnN0YWxsZXIgdGhyZXcgYW4gdW5leHBlY3RlZCBlcnJvclxuU3lzdGVtLkludmFsaWRPcGVyYXRpb25FeGNlcHRpb246IEFuIGludmFsaWQgcmVxdWVzdCBVUkkgd2FzIHByb3ZpZGVkLiBUaGUgcmVxdWVzdCBVUkkgbXVzdCBlaXRoZXIgYmUgYW4gYWJzb2x1dGUgVVJJIG9yIEJhc2VBZGRyZXNzIG11c3QgYmUgc2V0LlxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENsaWVudC5QcmVwYXJlUmVxdWVzdE1lc3NhZ2UoSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3QpXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cC5IdHRwQ2xpZW50LlNlbmRBc3luYyhIdHRwUmVxdWVzdE1lc3NhZ2UgcmVxdWVzdCwgSHR0cENvbXBsZXRpb25PcHRpb24gY29tcGxldGlvbk9wdGlvbiwgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlBsdWdpbk1hbmFnZXIuSW5zdGFsbFBsdWdpbkFzeW5jKFJlbW90ZVBsdWdpbk1hbmlmZXN0IHJlcG9NYW5pZmVzdCwgQm9vbGVhbiB1c2VUZXN0aW5nLCBQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcUGx1Z2luTWFuYWdlci5jczpsaW5lIDQxMiJ9
--------------------------------
10:33:47.666 | ERR [PLUGINW] Plugin installer threw an unexpected error
System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 412
--------------------------------

```

i'm checking what can be wrong on my end...

**Comment by Lanselotto** [comment]
yeah, same error

```
2021-09-27 15:40:21.674 +02:00 [DBG] [PLUGINM] Installing plugin Echoglossian (testing=False)
--------------------------------
2021-09-27 15:40:21.676 +02:00 [VRB] [PLUGINM] Assembly.Location // System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a // C:\Users\User\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\5.0.6\System.Net.Http.dll
--------------------------------
2021-09-27 15:40:21.679 +02:00 [VRB] [PLUGINM] Assembly.Location // System.Net.Http, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a // C:\Users\User\AppData\Roaming\XIVLauncher\runtime\shared\Microsoft.NETCore.App\5.0.6\System.Net.Http.dll
--------------------------------
2021-09-27 15:40:21.688 +02:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.InvalidOperationException: An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 412
--------------------------------

**Comment by lokinmodar** [comment]
fixed!! Please reload and retry!
https://github.com/goatcorp/DalamudPlugins/commit/c277ddbf5cbc34d584bf88ed68e65626271c8fc2
